#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool flag = true;
	while (true)
	{
		if (flag == false)
		{
			while (flag == false)
			{
				wait1Msec(100);
				if( flag==false && SensorValue[dgtl1] == true )
					flag=true;
				motor[port6] = 20;
				if( flag==false && SensorValue[dgtl1] == true )
					flag=true;
				wait1Msec(300);
				if( flag==false && SensorValue[dgtl1] == true )
					flag=true;
				motor[port6] = -20;
				if( flag==false && SensorValue[dgtl1] == true )
					flag=true;
				wait1Msec(300);
			}
		} else
			{
				if( flag==true && SensorValue[dgtl1] == true )
				flag=false;
			}
	}
}
